### ISSUE TITLE
Need flexible ArrayOfByte tuple sketch with creation option from theta sketch

### ISSUE THREAD

**Issue by will-lauer** [apache/incubator-datasketches-java#213]
I'm building an Druid aggregator to do distinct counting with a frequency estimate (how many unique values that occurred a minimum number of times). To build this, I want to use an efficient tuple sketch implementation. Druid has an aggregator that uses the ArrayOfDouble tuple sketch, but I really want to do integral counting, so a LongTuple sketch would be ideal, but an ArrayOfByte tuple sketch would probably allow me the most flexibility, allowing me to treat the bytes as an int, long, or any other value that I want. 

For this to work, I would need to control how the tuple value to computed in both union and intersection collision cases. ArrayOfDouble assumes double sum when a union occurs, but allows an ArrayOfDoubleSketchCombiner instance to be used to compute the result in an intersection case. I would want the Combiner to be used for both Union, Intersection, and Difference (separate methods for each).

The other feature I need is the ability to create one of these new sketches from a theta sketch, providing a default value for the tuple. Its not hard to do this, but it requires access to some internals of the theta sketch. If the new tuple sketch lived in the same package as the theta sketch, it could access these. If not, some part of the protections in theta sketch would need to be loosened. In order to properly construct a tuple sketch from a theta sketch, it looks like I need access to Sketch.getCache(), SKetch.getThetaLong(), and Sketch.getSeedHash().

**Comment by leerho** [comment]
Alex is OOO until Tuesday. He is the right one to address this.

**Comment by AlexanderSaydakov** [comment]
I think that having an ArrayOfBytes in addition to ArrayOfDoubles makes a lot of sense.

I agree that assuming a sum for combining values during the union operation was not the best choice. A user-provided combiner (the same way as for intersection) makes a lot of sense.

Set difference does not need to combine values since the keys don't overlap.

Regarding construction of Tuple sketches from Theta. I believe it makes sense, but not sure how to implement that without opening up the parts of the Theta API, which we wanted to keep private. Perhaps, this can be done using reflection. On the other hand, I personally don't think it would be a big deal to have a public iterator over the Theta sketch (instead of getCache()) just like we already have for Tuple sketch. The motivation for Tuple sketches was access to values, of course, not keys. I wouldn't allow getSeedHash(), but require providing the seed for this operation instead (just like for deserialization, for instance). And allowing getThetaLong() doesn't seem to be a big deal to me. It does seem to be a "technical" method, not really needed by the end user, so we didn't want to clutter the API unnecessarily.

**Comment by will-lauer** [comment]
On the topic of getSeedHash(), if you are constructing one sketch from another, I don't see any real need to pass the seed in again. There is no new hashing going on in this case.

**Comment by leerho** [comment]
getThetaLong() and getIterator() is now checked into master.  I had not seen your last comment, so I need to think about the seedHash issue some more.  Implementing the iterator was a little tricky but it works for all variations of Theta sketches: Alpha, Compact, Direct, SingleItem, etc.

**Comment by AlexanderSaydakov** [comment]
> if you are constructing one sketch from another, I don't see any real need to pass the seed in again. There is no new hashing going on in this case.

This is debatable. Let's say, we require seed to deserialize Theta sketches, even compact ones where update is not possible. Was this necessary? Probably not. The alternative is opening up getSeedHash(). I am not sure which way to go. Perhaps, providing the seed for conversion is a bit cleaner.

**Comment by leerho** [comment]
This is a well understood feature request and we will likely address this when we do a major restructuring of the Theta sketch packages.  I will close this for now as we can reopen if necessary.
